id: ID23696A5
legacy_id: P006628
ocr_import_info:
  bdrc_scan_id: W1KG17575
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T03:27:52'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T09:38:56.376049+00:00'
last_modified: 2022-08-31 17:39:04.086465
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG17575
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG17575
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་ཀྱཻ་རྡོ་རྗེའི་དབང་གི་ཆུ་བོ་ཆེན་མོ་མཛེས་པར་བྱེད་པའི་རྒྱན་ནག་འགྲོས་བཀླག་ཆོག་ཏུ་བཀོད་པ་སྭ་ར་སྭ་སྟིའི་ཀླུང་ཆེན་བདུད་རྩིའི་རྒྱུན་འབབ།
  author: ས་སྐྱ་ཁྲི་ཆེན ༤༢་ངག་དབང་ཀུན་དགའ་ཐེག་ཆེན་དཔལ་འབར།
statistics:
  ocr_word_mean_confidence_index: 0.8640846097258756
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I1KG17934:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17934
      total_pages: 146
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG17934.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8640846097258756
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
