id: P006628
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17575
  title: དཔལ་ཀྱཻ་རྡོ་རྗེའི་དབང་གི་ཆུ་བོ་ཆེན་མོ་མཛེས་པར་བྱེད་པའི་རྒྱན་ནག་འགྲོས་བཀླག་ཆོག་ཏུ་བཀོད་པ་སྭ་ར་སྭ་སྟིའི་ཀླུང་ཆེན་བདུད་རྩིའི་རྒྱུན་འབབ།
  author: ''
  volumes:
    7d804cae65294801ba803173ada835cd:
      image_group_id: I1KG17934
      title: ''
      volume_number: 1
      total_pages: 146
