id: P006628
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17575
  title: དཔལ་ཀྱཻ་རྡོ་རྗེའི་དབང་གི་ཆུ་བོ་ཆེན་མོ་མཛེས་པར་བྱེད་པའི་རྒྱན་ནག་འགྲོས་བཀླག་ཆོག་ཏུ་བཀོད་པ་སྭ་ར་སྭ་སྟིའི་ཀླུང་ཆེན་བདུད་རྩིའི་རྒྱུན་འབབ།
  author: ''
  volumes: {}
